In [0]:
import numpy as np
import pandas as pd

In [0]:
c_v=pd.read_excel("/content/TimeSeries_KeyIndicators_Detail.xlsx")

In [6]:
c_v

          Date Province_Old  ...  Confirmed_HW_-_Active_Deaths  Unnamed:_53
0   2020-04-04          AJK  ...                             0          NaN
1   2020-04-04  Balochistan  ...                             0          NaN
2   2020-04-04           GB  ...                             0          NaN
3   2020-04-04          ICT  ...                             0          NaN
4   2020-04-04           KP  ...                             0          NaN
..         ...          ...  ...                           ...          ...
233 2020-05-13           GB  ...                            17          2.0
234 2020-05-13          ICT  ...                             7          1.0
235 2020-05-13           KP  ...                            57          2.0
236 2020-05-13       Punjab  ...                            72          0.0
237 2020-05-13        Sindh  ...                            30          5.0

[238 rows x 54 columns]

In [5]:
c_v.columns=c_v.columns.str.strip().str.replace(' ','_')
c_v

          Date Province_Old  ...  Confirmed_HW_-_Active_Deaths  Unnamed:_53
0   2020-04-04          AJK  ...                             0          NaN
1   2020-04-04  Balochistan  ...                             0          NaN
2   2020-04-04           GB  ...                             0          NaN
3   2020-04-04          ICT  ...                             0          NaN
4   2020-04-04           KP  ...                             0          NaN
..         ...          ...  ...                           ...          ...
233 2020-05-13           GB  ...                            17          2.0
234 2020-05-13          ICT  ...                             7          1.0
235 2020-05-13           KP  ...                            57          2.0
236 2020-05-13       Punjab  ...                            72          0.0
237 2020-05-13        Sindh  ...                            30          5.0

[238 rows x 54 columns]

In [0]:
c_v.rename(columns={'ProvinceOld':'Province_Old','Suspected Cases Last Date':'Suspected_Cases_Last_Date','Suspected Cases Last 24 Hrs':'Suspected_Cases_Last_24_Hrs','Suspected Cases Cumulative':'Suspected_Cases_Cumulative',
                   'Lab Tests Last 24 Hrs':'Lab_Tests_Last_24_Hrs','Lab Tests Cumulative':'Lab_Tests_Cumulative','Confirmed Cases Last Date':'Confirmed_Cases_Last_Date',
                   'Confirmed Cases Last 24 Hrs':'Confirmed_Cases_Last_24_Hrs','Confirmed Cases Cumulative':'Confirmed_Cases_Cumulative','Confirmed HW - Active Nurses':'Confirmed_HW_Active_Nurses',
                   'Confirmed HW - Active Others':'Confirmed_HW_Active_Others','Confirmed HW - Active Total':'Confirmed_HW_Active_Total','Confirmed HW - Active Isolation':'Confirmed_HW_Active_Isolation',
                   'Confirmed HW - Active Hospital':'Confirmed_HW_Active_Hospital','Confirmd HW - Active Hospital Stable':'Confirmed_HW_Active_Hospital _Stable','Confirmed HW - Active Hospital Ventilator':'Confirmed_HW_Active_Hospital_Ventilator',
                   'Confirmed HW - Active Recovered':'Confirmed_HW_Active_Recovered','Confirmed HW - Active Deaths':'Confirmed_HW_Active_Deaths','Confirmed HW - Active Doctors':'Confirmed_HW_Active_Doctors','Confirmed HW - Active Hospital Stable':'Confirmed_HW_Active_Hospital_Stable'},inplace=True)

In [10]:
c_v.head()

        Date Province_Old  ...  Confirmed_HW_-_Active_Deaths  Unnamed:_53
0 2020-04-04          AJK  ...                             0          NaN
1 2020-04-04  Balochistan  ...                             0          NaN
2 2020-04-04           GB  ...                             0          NaN
3 2020-04-04          ICT  ...                             0          NaN
4 2020-04-04           KP  ...                             0          NaN

[5 rows x 54 columns]

In [14]:
c_v.drop('Unnamed:_53',axis=1,inplace=True)
c_v

          Date  ... Confirmed_HW_-_Active_Deaths
0   2020-04-04  ...                            0
1   2020-04-04  ...                            0
2   2020-04-04  ...                            0
3   2020-04-04  ...                            0
4   2020-04-04  ...                            0
..         ...  ...                          ...
233 2020-05-13  ...                           17
234 2020-05-13  ...                            7
235 2020-05-13  ...                           57
236 2020-05-13  ...                           72
237 2020-05-13  ...                           30

[238 rows x 53 columns]

In [15]:
c_v.isnull().sum()

Date                                         0
Province_Old                                 0
Suspected_Cases_Last_Date                    0
Suspected_Cases_Last_24_Hrs                  0
Suspected_Cases_Cumulative                   0
Lab_Tests_Last_24_Hrs                        0
Lab_Tests_Cumulative                         0
Confirmed_Cases_Last_Date                    0
Confirmed_Cases_Last_24_Hrs                  0
Confirmed_Cases_Cumulative                   0
Deaths_Last_Date                             0
Deaths_Last_24_Hrs                           0
Deaths_Cumulative                            0
Deaths_Ventilator_Last_24_Hrs                0
Transmission_Total                           0
Transmission_Foreign_-_Iran                  0
Transmission_Foreign_-_Iran_%                0
Transmission_Foreign_-_Other                 0
Transmission_Foreign_-_Other_%               0
Transmission_Local_-_Tableegh                0
Transmission_Local_%_-_Tableegh              0
Transmission_Local_-_Others                  0
Transmission_Local_%_-_Others                0
Transmission_Local                           0
Transmission_Local_%                         0
Total_Hospitals                              0
Beds_for_COVID                               0
Total_Admitted                               0
Admitted_Stable                              0
Admitted_Critical                            0
Admitted_Venilator                           0
Home_Quarantine                              0
Recovered                                    0
Death                                        0
Quarantine_Facilities                        0
Last_24_Hrs_Arrival                          0
Last_24_Hrs_(Location)                       0
Last_24_Hrs_Departure                        0
Cumulative_Quarantined                       0
Number_of_Tests                              0
Results_Achieved                             0
Test_Positive_Cases                          0
Test_Positive_Cases_%                        0
Confirmed_HW_-_Active_Doctors                0
Confirmed_HW_-_Active_Nurses                 0
Confirmed_HW_-_Active_Others                 0
Confirmed_HW_-_Active_Total                  0
Confirmed_HW_-_Active_Isolation              0
Confirmed_HW_-_Active_Hospital               0
Confirmed_HW_-_Active_Hospital_Stable        0
Confirmed_HW_-_Active_Hospital_Ventilator    0
Confirmed_HW_-_Active_Recovered              0
Confirmed_HW_-_Active_Deaths                 0
dtype: int64

In [16]:
c_v['Date']=pd.to_datetime(c_v.Date)
c_v['Date']

0     2020-04-04
1     2020-04-04
2     2020-04-04
3     2020-04-04
4     2020-04-04
         ...
233   2020-05-13
234   2020-05-13
235   2020-05-13
236   2020-05-13
237   2020-05-13
Name: Date, Length: 238, dtype: datetime64[ns]

# **Cleaned Data**

In [17]:
c_v.describe()

       Suspected_Cases_Last_Date  ...  Confirmed_HW_-_Active_Deaths
count                 238.000000  ...                    238.000000
mean                14506.382353  ...                      3.357143
std                 20186.887585  ...                     11.498788
min                   322.000000  ...                      0.000000
25%                  2873.750000  ...                      0.000000
50%                  6018.000000  ...                      0.000000
75%                 16610.250000  ...                      1.000000
max                107603.000000  ...                     72.000000

[8 rows x 51 columns]

# **Saving data back to Excel file**

In [0]:
c_v.to_excel('/content/TimeSeries_KeyIndicators_Detail.xlsx')